version: '3.9'

services:
  nestjs_postgres:
    container_name: bib_postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
    - ./data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - breakfastinbed

  pgadmin:
      links:
      - postgres:postgres
      container_name: pgadmin
      image: dpage/pgadmin4
      ports:
      - "8088:80"
      volumes:
      - ./data/pgadmin:/root/.pgadmin
      env_file:
      - docker.env
      networks:
      - breakfastinbed
      depends_on:
        - nestjs_postgres
networks:
  breakfastinbed:
   driver: bridge